apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{.Values.namespace}}
  labels:
    component: {{ .Values.serviceName }}
    type: {{ .Values.serviceName }}
    name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    type: {{ .Values.serviceName }}
    service: {{ .Values.serviceName }}
    name: {{ .Values.serviceName }}
